### PR TITLE
move deepchecks install to Dockerfile

### PR DESCRIPTION
**Pull request by stephqwu**
Address [this issue](https://github.com/UBC-MDS/heart_disease_predictor_py/issues/50)

### CODE REVIEW

**Comment by stephqwu** [comment]
to trigger workflow automatically

**Comment by Arc-Celt** [comment]
After pulling the latest tag with `docker pull achalim/heart_disease_predictor_py:latest` and run it with `docker run --rm -p 8888:8888 achalim/heart_disease_predictor_py:latest`, I tested the deepchecks import and found it was successfully installed. The issue should be fixed now. Thanks Stephanie! I will pin the version of pip in the environment.yml and remove the deepchecks there in a later commit.

**Comment by stephqwu** [comment]
Sounds good, thank you Archer

**Review by Arc-Celt — APPROVED** [review]
The deepchecks is successfully imported in the latest image. It's OK to merge now.

**Comment by stephqwu** [comment]
The pip version looks successfully pinned as well

I ran with `docker-compose up` instead of `docker run --rm -p 8888:8888 achalim/heart_disease_predictor_py:latest`

Merging

**Pull request merged**
