### PR TITLE
Fix the things TA mentioned for milestone 1

### PR DESCRIPTION
**Pull request by Arc-Celt**
- Ensure the environment YAML file explicitly includes the version of each package.
- Update the conda-lock file to align with the YAML file.
- Separate Licenses for Code (MIT) and Report (CC0).
- Correct Typos of conda environment names in README.md.

### CODE REVIEW

**Comment by stephqwu** [comment]
python==3.11 to avoid the big bug

**Review by stephqwu — CHANGES_REQUESTED** [review]
python==3.11

**Comment by Arc-Celt** [comment]
We have currently deleted conda-lock.yml file. But in the future if we have conda-linux-64.lock, we should change the instructions in the README.md as well.

**Review by stephqwu — APPROVED** [review]
Looks good now

**Pull request merged**
