### PR TITLE
Creating documentations files

### PR DESCRIPTION
**Pull request by Albert0011**
- First init environment.yml
- Create CONTRIBUTING.md
- Create CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by stephqwu** [comment]
Looks good, though keep in mind we still have to add Conda lock files for each major operating system (or the corresponding renv files) can merge this first though

**Review by stephqwu — APPROVED** [review]
Looks good, though keep in mind we still have to add Conda lock files for each major operating system (or the corresponding renv files) can merge this first though

**Comment by Albert0011** [comment]
Done added the files!

**Comment by stephqwu** [comment]
Works on my MacBook Pro

**Comment by stephqwu** [comment]
Works now

**Pull request merged**
