### PR TITLE
Add scripts folder with download_data script

### PR DESCRIPTION
**Pull request by stephqwu**

### CODE REVIEW

**Comment by Arc-Celt** [comment]
What do you think about updating the README.md simultaneously to include the bash command for running the script (like Tiffany's example below)? It could make code reviewing and testing way easier!

3. To run the analysis, open a terminal and run the following commands:
```
python scripts/download_data.py \
    --url="..." \
    --write-to=data/raw
```

**Comment by Albert0011** [comment]
I dont mind, looks good

**Comment by Arc-Celt** [comment]
yeah just thought it might take some time for the reviewer to figure out the parameters (especially for the model fitting and scoring scripts later

**Comment by stephqwu** [comment]
Question, so would I be adding a README commit to each script PR before it gets reviewed and merged?

**Comment by Arc-Celt** [comment]
You know what, how about prividing the bash command for running the script under the issue, so the person who reviews can use it. I agree that README can wait until the code can successfully run.

**Comment by stephqwu** [comment]
Sounds good to me

**Review by Arc-Celt — APPROVED** [review]
Looks neat and runs on my pc. Should be able to merge.

**Pull request merged**
