### PR TITLE
updated readme with docker

### PR DESCRIPTION
**Pull request by cherylziunzhao**
- Pulling and running the Docker container.
- Updating the Docker container with new dependencies.
- Using Docker Compose for easier setup.

### CODE REVIEW

**Comment by Arc-Celt** [comment]
I found there was still a mistake in the MIT License and fixed that just now.

**Comment by Arc-Celt** [comment]
Some packages are not used but shown in the yml file. I'll only keep the used packages in our project.

**Comment by Arc-Celt** [comment]
We'll fix the stuffs in the new branch docker. The changes in the documentation branch are ok to be merged first.

**Comment by Albert0011** [comment]
Looks good to me!

**Pull request merged**
